# Generated by Django 5.0.6 on 2024-05-13 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cards')),
                ('shots', models.IntegerField()),
                ('sheild', models.BooleanField()),
                ('disapear', models.BooleanField()),
                ('allsheild', models.BooleanField()),
                ('disable', models.IntegerField()),
                ('repeat_disable', models.BooleanField()),
                ('bomb', models.BooleanField()),
                ('fast_bomb', models.BooleanField()),
                ('waking', models.IntegerField()),
                ('gun', models.IntegerField()),
                ('fake_gun', models.IntegerField()),
                ('query', models.IntegerField()),
                ('heal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.rolecard')),
            ],
        ),
        migrations.CreateModel(
            name='ZodiacRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('Winners', models.CharField(max_length=100)),
                ('roles', models.ManyToManyField(to='game.role')),
            ],
        ),
    ]
