# Generated by Django 5.0.6 on 2024-05-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamestatus_zodiacroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='speak_turn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gamestatus',
            name='day',
            field=models.BooleanField(default=True),
        ),
    ]
