# Generated by Django 5.0.6 on 2024-05-15 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamestatus_speak_turn_alter_gamestatus_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacGameStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('day', models.BooleanField(default=True)),
                ('speak_turn', models.IntegerField(null=True)),
                ('magicman', models.IntegerField(default=0)),
                ('bomber', models.BooleanField(default=False)),
                ('zodiac', models.IntegerField(default=0)),
                ('gunner_fake', models.IntegerField(default=0)),
                ('gunner_real', models.BooleanField(default=False)),
                ('died', models.ManyToManyField(related_name='dies', to='game.rolecard')),
                ('ocean', models.ManyToManyField(max_length=2, related_name='oceans', to='game.rolecard')),
            ],
        ),
        migrations.AlterField(
            model_name='zodiacroom',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.zodiacgamestatus'),
        ),
        migrations.DeleteModel(
            name='GameStatus',
        ),
    ]
