# Generated by Django 5.0.6 on 2024-05-15 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_zodiacgamestatus_alter_zodiacroom_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiacgamestatus',
            name='challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zodiacgamestatus',
            name='challenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.rolecard'),
        ),
        migrations.AddField(
            model_name='zodiacgamestatus',
            name='challenger_wanters',
            field=models.ManyToManyField(related_name='challenge_wanters', to='game.rolecard'),
        ),
        migrations.AddField(
            model_name='zodiacgamestatus',
            name='turns',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zodiacroom',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='game.zodiacgamestatus'),
        ),
    ]
