# Generated by Django 5.0.6 on 2024-05-15 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_zodiacgamestatus_challenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='challenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.role'),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='challenger_wanters',
            field=models.ManyToManyField(related_name='challenge_wanters', to='game.role'),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='died',
            field=models.ManyToManyField(related_name='dies', to='game.role'),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='ocean',
            field=models.ManyToManyField(max_length=2, related_name='oceans', to='game.role'),
        ),
        migrations.AlterField(
            model_name='zodiacroom',
            name='roles',
            field=models.ManyToManyField(max_length=12, to='game.role'),
        ),
    ]
