# Generated by Django 5.0.6 on 2024-05-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_zodiacgamestatus_challenger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='bomber',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='challenge',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='challenger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='challenger_wanters',
            field=models.ManyToManyField(blank=True, related_name='challenge_wanters', to='game.role'),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='day',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='died',
            field=models.ManyToManyField(blank=True, related_name='dies', to='game.role'),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='gunner_fake',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='gunner_real',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='magicman',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='ocean',
            field=models.ManyToManyField(blank=True, max_length=2, related_name='oceans', to='game.role'),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='room_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='speak_turn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='turns',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='zodiacgamestatus',
            name='zodiac',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
